### ISSUE TITLE
🚀[FEA]: Download support from CDS api for training weather models

### ISSUE THREAD

**Issue by loliverhennigh** [NVIDIA/modulus-launch#103]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

Currently the weather and climate examples are not usable because of dataset access issues. While there may be better longer term solutions this feature will add scripts to download the ERA5 dataset from the CDS api.

**Comment by NickGeneva** [comment]
Merged in https://github.com/NVIDIA/modulus-launch/pull/104
