### ISSUE TITLE
🚀[FEA]:  Basic unified training recipe for AFNO & SFNO (non-parallel)

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus-launch#48]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

Currently, the various weather prediction models within Modulus utilize distinct training recipes, each with unique requirements for configurations, multi-step rollouts, checkpoint saving and loading, runtime optimizations, static datasets, and data loading. This can be cumbersome for new users, who must familiarize themselves with the separate requirements of each model. As such, there is a clear need for a unified training recipe that can facilitate quick experimentation across multiple models for users.
As a first tep, we can develop a basic unified recipe for AFNO and SFNO without model/tensor parallelization.

### Describe any alternatives you have considered

N/A

### Additional context

N/A

**Comment by NickGeneva** [comment]
Moved to core, closing
