### ISSUE TITLE
🐛[BUG]: License header checks output folders

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/modulus-launch#52]
### Version

0.1.0

### Describe the issue

License header check also looks at output / mlrun folders in the examples. There needs to be an added option for excluding folders with a given pattern.

**Comment by mnabian** [comment]
@NickGeneva I think there is already an option for excluding specific directories form the header test: https://github.com/NVIDIA/modulus-launch/blob/main/test/ci_tests/config.json#L5. Would this work?

**Comment by NickGeneva** [comment]
Fixed in: https://github.com/NVIDIA/modulus-launch/pull/61
